version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
    open-pull-requests-limit: 0
  # Python uv
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
    open-pull-requests-limit: 0
  # npm
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
    open-pull-requests-limit: 0
  # Docker
  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    open-pull-requests-limit: 0
  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    open-pull-requests-limit: 0
